### ISSUE TITLE
Template failing on Primary instance

### ISSUE THREAD

**Issue by abdul-git** [aws-quickstart/quickstart-oracle-database#6]
I tried to use quick start template for Oracle DB and even after multiple tries in different region seems to be failing on following:

The following resource(s) failed to create: [PrimaryInstance]. 

  | 09:23:58 UTC-0500 | CREATE_FAILED | AWS::CloudFormation::Stack | Oracle-Database-OracleStack-JCIJ8UDUB8Z3 | The following resource(s) failed to create: [PrimaryInstance].
-- | -- | -- | -- | -- | --
  | 09:23:56 UTC-0500 | CREATE_FAILED | AWS::EC2::Instance | PrimaryInstance | Received FAILURE signal with UniqueId i-03c29145254fd0b

logs from cloud-init:

Sep 20 10:21:24 localhost cloud-init: Installing : unzip-6.0-16.el7.x86_64                                      1/1
Sep 20 10:21:24 localhost cloud-init: Verifying  : unzip-6.0-16.el7.x86_64                                      1/1
Sep 20 10:21:24 localhost cloud-init: Installed:
Sep 20 10:21:24 localhost cloud-init: unzip.x86_64 0:6.0-16.el7
Sep 20 10:21:24 localhost cloud-init: Complete!
Sep 20 10:23:49 localhost cloud-init: 2017-09-20 10:23:49,884 - templater.py[WARNING]: Cheetah not available as the default renderer for unknown template, reverting to the basic renderer.
Sep 20 10:23:49 localhost cloud-init: Cloud-init v. 0.7.6 finished at Wed, 20 Sep 2017 14:23:49 +0000. Datasource DataSourceEc2.  Up 200.64 seconds

logs from cfn-init:

2017-09-20 10:21:29,505 [INFO] ConfigSets completed
2017-09-20 10:21:29,505 [DEBUG] Not clearing reboot trigger as scheduling support is not available
2017-09-20 10:21:29,506 [INFO] -----------------------Build complete-----------------------
2017-09-20 10:23:49,689 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-1.amazonaws.com
2017-09-20 10:23:49,689 [DEBUG] Signaling resource PrimaryInstance in stack Oracle-Database-OracleStack-JCIJ8UDUB8Z3 with unique ID i-03c29145254fd0b2f and status FAILURE

logs from bootstrap.log:

Calling ioctl() to re-read partition table.
Syncing disks.
mke2fs 1.42.9 (28-Dec-2013)
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
65536 inodes, 261888 blocks
13094 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=268435456
8 block groups
32768 blocks per group, 32768 fragments per group
8192 inodes per group
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376

Allocating group tables: 0/8^H^H^H   ^H^H^Hdone
Writing inode tables: 0/8^H^H^H   ^H^H^Hdone
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: 0/8^H^H^H   ^H^H^Hdone

Redirecting to /bin/systemctl start  rpcbind.service
Redirecting to /bin/systemctl start  nfs.service
Redirecting to /bin/systemctl start  nfslock.service
/dev/xvdy1       1014680    2564    943356   1% /shared
QS_SHARED_FS|SUCCESS
QS_File_Systems_Mounted
QS_BEGIN_media_download
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by StylusEater** [comment]
@abdul-git do you have an error message or some other output? There should be a few logs in the /tmp directory of the primary instance. In particular, please attach /tmp/bootstrap.log and if it exists /tmp/oracleexec.log.

**Comment by abdul-git** [comment]
![image](https://user-images.githubusercontent.com/6741506/30649966-4ff50d3a-9de7-11e7-99e7-f723f2018199.png)

**Comment by StylusEater** [comment]
Would you please include the rest of the events in your screenshot?

**Comment by StylusEater** [comment]
I see the issue:

`QS_BEGIN_media_download
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

You do not have the proper permissions to access the S3 bucket. Did you create the S3 bucket with the installation media files required for the installation to succeed?

Please read the following links to learn how to prepare your account for installation:

* http://docs.aws.amazon.com/quickstart/latest/oracle-database/deployment.html
* http://docs.aws.amazon.com/quickstart/latest/oracle-database/step-1.html
* http://docs.aws.amazon.com/quickstart/latest/oracle-database/step-3.html

**Comment by abdul-git** [comment]
Hi - Thanks for looking into this - Yes, Oracle binaries are staged in S3 buckets and I do see the files get copied to EC2 database instance.

**Comment by abdul-git** [comment]
[bootstrap.txt](https://github.com/aws-quickstart/quickstart-oracle-database/files/1319067/bootstrap.txt)
Here is the screen shot of Oracle binaries being pulled from S3
![image](https://user-images.githubusercontent.com/6741506/30665074-72bef8a2-9e15-11e7-8972-5e65710d4151.png)


Attaching bootstrap.log

**Comment by abdul-git** [comment]
I agree - I will try out again with different account and report back, but if possible can you try it as well? I am wondering if something changed with template..

**Comment by StylusEater** [comment]
I use this template regularly but with many modifications. As far as I know, everything works...the error you are receiving is due to an S3 permissions issue as indicated. Please correct it and try again.

**Comment by abdul-git** [comment]
Thanks for your help! it certainly looks like something with S3 (even though permissions are set to public), I tried with another account and it seems to be humming along.

**Comment by StylusEater** [comment]
Happy to help. Please close the issue when you have a moment.

**Comment by abdul-git** [comment]
issue resolved - thanks for the help..

**Comment by santiagocardenas** [comment]
Thank you @StylusEater for helping out.

We're curious to learn how you've been using this Quick Start. Please reach out to us via quickstart@amazon.com

Thanks,
Santiago
